from __future__ import annotations

"""Historical Market Brain priors for LIVE tender retrieval ranking.

This layer is deliberately weak and pre-DCE only. Historical evidence may help
choose which live notices deserve scarce DCE retrieval compute, but it can never
satisfy an eligibility gate, alter evidence_quality, or create a final GREEN.

Expected compact JSON contract::

  {
    "contract": "TENDER_MARKET_BRAIN_PRIORS_V1",
    "status": "READY",
    "source_release": "tender-global-market-intelligence-v4",
    "country_cpv": {
      "FRA|72": {
        "sample_size": 1234,
        "priority_bonus": 6,
        "repeat_buyer_rate": 0.31,
        "supplier_concentration": 0.08,
        "value_coverage": 0.72
      }
    },
    "buyers": {
      "fra|region bourgogne franche comte": {
        "sample_size": 19,
        "priority_bonus": 4,
        "repeat_procurements": 19
      }
    }
  }

priority_bonus is generated by the historical analytics builder and clamped again
here. The live engine does not derive missing historical facts by itself.
"""

import json
import re
from pathlib import Path
from typing import Any

CONTRACT = "TENDER_MARKET_BRAIN_PRIORS_V1"
MAX_COUNTRY_CPV_BONUS = 8
MAX_BUYER_BONUS = 6
MAX_TOTAL_BONUS = 12
MIN_SAMPLE = 8


def _norm(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "").strip()).casefold()


def _country(rec: dict) -> str:
    for key in ("country", "country_code", "buyer_country"):
        value = str(rec.get(key) or "").strip().upper()
        if value:
            return value
    return ""


def _cpv(rec: dict) -> str:
    raw = rec.get("cpv") or rec.get("cpv_code") or rec.get("main_cpv") or ""
    if isinstance(raw, list):
        raw = raw[0] if raw else ""
    digits = re.sub(r"\D", "", str(raw))
    # CPV division is the most stable cross-source historical grain.
    return digits[:2] if len(digits) >= 2 else ""


def _buyer(rec: dict) -> str:
    return _norm(rec.get("buyer") or rec.get("buyer_name") or rec.get("authority"))


def load(path: str | Path = "control/historical_market_priors.json") -> dict:
    p = Path(path)
    if not p.is_file():
        return {}
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}
    if not isinstance(data, dict) or data.get("contract") != CONTRACT or data.get("status") != "READY":
        return {}
    return data


def adjustment(rec: dict, priors: dict | None) -> tuple[int, list[str]]:
    if not priors:
        return 0, []
    delta = 0
    reasons: list[str] = []
    country = _country(rec)
    cpv = _cpv(rec)

    if country and cpv:
        row = ((priors.get("country_cpv") or {}).get(f"{country}|{cpv}") or {})
        n = int(row.get("sample_size") or 0)
        if n >= MIN_SAMPLE:
            raw = int(round(float(row.get("priority_bonus") or 0)))
            bonus = max(-MAX_COUNTRY_CPV_BONUS, min(MAX_COUNTRY_CPV_BONUS, raw))
            delta += bonus
            if bonus:
                reasons.append(f"{bonus:+d}:historical-country-cpv(n={n})")

    buyer = _buyer(rec)
    if country and buyer:
        row = ((priors.get("buyers") or {}).get(f"{country.casefold()}|{buyer}") or {})
        n = int(row.get("sample_size") or 0)
        if n >= MIN_SAMPLE:
            raw = int(round(float(row.get("priority_bonus") or 0)))
            bonus = max(-MAX_BUYER_BONUS, min(MAX_BUYER_BONUS, raw))
            delta += bonus
            if bonus:
                reasons.append(f"{bonus:+d}:historical-buyer(n={n})")

    return max(-MAX_TOTAL_BONUS, min(MAX_TOTAL_BONUS, delta)), reasons
