#!/usr/bin/env python3
from __future__ import annotations
import argparse,csv,json
from pathlib import Path
import duckdb

def write(path,header,rows):
 p=Path(path);p.parent.mkdir(parents=True,exist_ok=True)
 with p.open('w',encoding='utf-8',newline='') as f:w=csv.writer(f);w.writerow(header);w.writerows(rows)

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--historical',required=True);ap.add_argument('--awards',required=True);ap.add_argument('--bridge',required=True);ap.add_argument('--out',required=True);a=ap.parse_args();out=Path(a.out);out.mkdir(parents=True,exist_ok=True)
 con=duckdb.connect();con.execute('SET threads=4');con.execute("SET memory_limit='5GB'")
 h=f"read_parquet('{a.historical}')";aw=f"read_parquet('{a.awards}')";br=f"read_parquet('{a.bridge}')"
 con.execute(f"""CREATE TABLE hh AS SELECT Historical_Tender_ID tender_id,Country country,upper(coalesce(nullif(Currency,''),'UNKNOWN')) currency,Buyer_Name buyer,Title title,Scope_Summary scope_summary,Procedure procedure_text,coalesce(Main_CPV,'') main_cpv,coalesce(Raw_CPV_Description,'') cpv_description,try_cast(Official_Estimated_Value as double) estimated_value,lower(coalesce(Title,'')) title_l,lower(concat_ws(' ',coalesce(Title,''),coalesce(Scope_Summary,''),coalesce(Raw_CPV_Description,''))) txt FROM {h}""")
 # Precision family rules. We intentionally split clerical entry, research collection, metadata, OCR, and digitization.
 con.execute("""CREATE TABLE c0 AS SELECT *,CASE
  WHEN regexp_matches(txt,'(?i)(rapid evidence review|systematic review|evidence synthesis|rapid evidence assessment|literature review service|research synthesis|revue de litt[ée]rature|revue documentaire)') THEN 'EVIDENCE_LITERATURE_SYNTHESIS'
  WHEN regexp_matches(txt,'(?i)(desk research|documentary research|desktop research|benchmarking study|benchmark study|market intelligence research|secondary research)') THEN 'DESK_RESEARCH_BENCHMARKING'
  WHEN regexp_matches(txt,'(?i)(data cleaning|data cleansing|data enrichment|data deduplication|data de-duplication|master data management|\bmdm\b|data quality remediation|datenbereinigung|nettoyage de donn[ée]es)') THEN 'DATA_CLEANING_ENRICHMENT_MDM'
  WHEN regexp_matches(txt,'(?i)(collection,? codification,? validation|data validation service|data verification service|record validation|validation of records|coding and validation|codification.*records|validation.*statistical records)') THEN 'DATA_VALIDATION_CODING'
  WHEN regexp_matches(txt,'(?i)(data entry services?|data keying|key data entry|manual data entry|saisie de donn[ée]es|dateneingabe|gegevensinvoer)') THEN 'DATA_ENTRY_KEYING'
  WHEN regexp_matches(txt,'(?i)(data collection services?|research data collection|survey data collection|field data collection|Datenerfassungs- und Recherchedienstleistungen)') THEN 'DATA_COLLECTION_RESEARCH'
  WHEN regexp_matches(txt,'(?i)(metadata creation|metadata enrichment|metadata management|metadata tagging|bibliographic metadata|bibliographic records|cataloguing services|cataloging services|Katalogisierung|catalogisering|catalogage documentaire|indexing services|document indexing)') THEN 'METADATA_CATALOGUING_INDEXING'
  WHEN regexp_matches(txt,'(?i)(ocr services|optical character recognition|ocr extraction|text extraction.*documents?|document.*text extraction)') THEN 'OCR_TEXT_EXTRACTION'
  WHEN regexp_matches(txt,'(?i)(document scanning services?|scanning and indexing services?|archive digitisation services?|archive digitization services?|digitisation of archives|digitization of archives|num[ée]risation des archives|num[ée]risation de documents|digitisation services|digitization services)') THEN 'DOCUMENT_DIGITIZATION_SERVICES'
  WHEN regexp_matches(txt,'(?i)(content migration services?|data migration services?|document migration services?|records migration|migration de donn[ée]es|datenmigration|gegevensmigratie)') THEN 'CONTENT_DATA_MIGRATION'
  WHEN regexp_matches(txt,'(?i)(document conversion services?|data conversion services?|file format conversion|document format conversion|conversion de documents|xml conversion|pdf conversion)') THEN 'DOCUMENT_DATA_CONVERSION'
  WHEN regexp_matches(txt,'(?i)(document redaction services?|redaction services|document anonymi[sz]ation|anonymi[sz]ation of documents|caviardage de documents)') THEN 'DOCUMENT_REDACTION_ANONYMIZATION'
  WHEN regexp_matches(txt,'(?i)(e-discovery|ediscovery|electronic discovery|legal document review|litigation document review|disclosure review services?)') THEN 'E_DISCOVERY_DOCUMENT_REVIEW'
  WHEN regexp_matches(txt,'(?i)(survey coding|questionnaire coding|open[- ]ended response coding|survey tabulation|survey data processing|survey data cleaning)') THEN 'SURVEY_DATA_PROCESSING'
  WHEN regexp_matches(txt,'(?i)(data annotation services?|data labelling services?|data labeling services?|image annotation services?|text annotation services?|training data annotation|ground truth annotation)') THEN 'DATA_ANNOTATION_LABELING'
  WHEN regexp_matches(txt,'(?i)(database maintenance services?|database updating services?|database population services?|registry maintenance services?|register maintenance services?)') THEN 'DATABASE_REGISTRY_OPERATIONS'
  WHEN regexp_matches(txt,'(?i)(knowledge base maintenance|knowledge base content|knowledge capture services?|knowledge management services?)') THEN 'KNOWLEDGE_CONTENT_OPERATIONS'
  ELSE NULL END info_family FROM hh""")
 # Semantic negatives are classification exclusions only: underlying records remain canonical and are counted separately.
 con.execute("""CREATE TABLE c AS SELECT *,CASE
  WHEN info_family IS NULL THEN NULL
  WHEN regexp_matches(txt,'(?i)(medical imaging|pathology slide|anatomopathology|scanner de lames|slide scanner|radiology|mammography|laser system|optical parametric|hardware scanner|supply.*scanner|fourniture.*scanner|medical device)') THEN 'SEMANTIC_COLLISION_OR_EQUIPMENT'
  WHEN regexp_matches(txt,'(?i)(physical storage|offsite storage|box storage|warehouse|warehousing|microfilm|microfiche|paper archive|hard copy|physical files|collection and transport.*archive)') THEN 'PHYSICAL_INPUT_OR_STORAGE'
  WHEN regexp_matches(txt,'(?i)(onsite|on-site|on site|sur site|at the premises)') THEN 'ONSITE_OR_LOCATION_DEPENDENT'
  WHEN info_family='E_DISCOVERY_DOCUMENT_REVIEW' THEN 'LEGAL_SPECIALIST_RISK'
  WHEN info_family='DOCUMENT_DIGITIZATION_SERVICES' THEN 'PHYSICAL_INPUT_LIKELY'
  ELSE 'DIGITAL_FIRST_OR_REMOTE_PLAUSIBLE' END delivery_flag,
  CASE WHEN info_family IS NOT NULL AND regexp_matches(title_l,'(?i)(evidence|literature|desk research|benchmark|data|metadata|catalogu|index|ocr|digit|scan|migration|conversion|redaction|anonym|e-discovery|ediscovery|survey|annotation|database|registry|knowledge)') THEN 'TITLE_SIGNAL' WHEN info_family IS NOT NULL THEN 'SCOPE_SIGNAL' ELSE NULL END signal_source
 FROM c0 WHERE info_family IS NOT NULL""")
 con.execute(f"CREATE TABLE astat AS SELECT Historical_Tender_ID tender_id,median(try_cast(Award_Value as double)) FILTER(WHERE try_cast(Award_Value as double)>=0) award_value,median(try_cast(Bidder_Count as double)) FILTER(WHERE try_cast(Bidder_Count as double)>=0) bidder_count FROM {aw} GROUP BY 1")
 con.execute(f"""CREATE TABLE ts AS WITH b0 AS (SELECT Award_ID award_id,coalesce(nullif(Supplier_ID,''),nullif(Supplier_Name,''),'UNKNOWN_SUPPLIER') sid,coalesce(nullif(Supplier_Name,''),nullif(Supplier_ID,''),'UNKNOWN_SUPPLIER') sname FROM {br}),bn AS (SELECT *,count(*) over(partition by award_id) n FROM b0),aa AS (SELECT Award_ID award_id,Historical_Tender_ID tender_id FROM {aw}) SELECT aa.tender_id,bn.sid,bn.sname,1.0/nullif(bn.n,0) w FROM aa JOIN bn USING(award_id)""")
 con.execute("CREATE TABLE p AS SELECT c.*,coalesce(a.award_value,c.estimated_value) reference_value,a.bidder_count FROM c LEFT JOIN astat a USING(tender_id) WHERE delivery_flag<>'SEMANTIC_COLLISION_OR_EQUIPMENT'")
 con.execute("CREATE TABLE bs0 AS SELECT info_family,delivery_flag,signal_source,country,currency,buyer,count(*) n FROM p WHERE buyer<>'' GROUP BY 1,2,3,4,5,6")
 con.execute("CREATE TABLE ss0 AS SELECT p.info_family,p.delivery_flag,p.signal_source,p.country,p.currency,t.sid,any_value(t.sname) supplier,sum(t.w) n FROM p JOIN ts t USING(tender_id) WHERE t.sid<>'UNKNOWN_SUPPLIER' GROUP BY 1,2,3,4,5,6")
 matrix=con.execute("""WITH b AS (SELECT info_family,delivery_flag,signal_source,country,currency,count(*) records,count(distinct nullif(buyer,'')) buyers,quantile_cont(reference_value,.25) FILTER(WHERE reference_value>=0) p25_value,median(reference_value) FILTER(WHERE reference_value>=0) median_value,quantile_cont(reference_value,.75) FILTER(WHERE reference_value>=0) p75_value,median(bidder_count) FILTER(WHERE bidder_count>=0) median_bidders FROM p GROUP BY 1,2,3,4,5),rb AS (SELECT info_family,delivery_flag,signal_source,country,currency,count(*) FILTER(WHERE n>=2) repeat_buyers FROM bs0 GROUP BY 1,2,3,4,5),ss AS (SELECT info_family,delivery_flag,signal_source,country,currency,count(*) suppliers,sum(n) linked_weight,max(n)/nullif(sum(n),0) top_supplier_share FROM ss0 GROUP BY 1,2,3,4,5) SELECT b.*,coalesce(rb.repeat_buyers,0),ss.suppliers,ss.linked_weight,ss.top_supplier_share FROM b LEFT JOIN rb USING(info_family,delivery_flag,signal_source,country,currency) LEFT JOIN ss USING(info_family,delivery_flag,signal_source,country,currency) ORDER BY records DESC,buyers DESC""").fetchall()
 write(out/'market_matrix.csv',['info_family','delivery_flag','signal_source','country','currency','records','buyers','p25_value','median_value','p75_value','median_bidders','repeat_buyers','suppliers','linked_weight','top_supplier_share'],matrix)
 fam=con.execute("""WITH b AS (SELECT info_family,count(*) records,count(distinct nullif(buyer,'')) buyers,median(reference_value) FILTER(WHERE reference_value>=0) median_value,median(bidder_count) FILTER(WHERE bidder_count>=0) median_bidders FROM p GROUP BY 1),s0 AS (SELECT info_family,sid,sum(n) n FROM ss0 GROUP BY 1,2),s AS (SELECT info_family,count(*) suppliers,max(n)/nullif(sum(n),0) top_supplier_share FROM s0 GROUP BY 1) SELECT b.*,s.suppliers,s.top_supplier_share FROM b LEFT JOIN s USING(info_family) ORDER BY records DESC""").fetchall();write(out/'family_summary.csv',['info_family','records','buyers','median_value','median_bidders','suppliers','top_supplier_share'],fam)
 winners=con.execute("""SELECT info_family,country,currency,supplier,n,n/nullif(sum(n) over(partition by info_family,country,currency),0) supplier_share FROM ss0 QUALIFY row_number() over(partition by info_family,country,currency order by n desc,supplier)<=15 ORDER BY info_family,country,currency,n DESC""").fetchall();write(out/'top_winners.csv',['info_family','country','currency','supplier','weighted_awards','supplier_share'],winners)
 buyers=con.execute("""SELECT info_family,country,currency,buyer,count(*) records FROM p WHERE buyer<>'' GROUP BY 1,2,3,4 QUALIFY row_number() over(partition by info_family,country,currency order by count(*) desc,buyer)<=15 ORDER BY info_family,country,currency,records DESC""").fetchall();write(out/'top_buyers.csv',['info_family','country','currency','buyer','records'],buyers)
 examples=con.execute("""SELECT info_family,delivery_flag,signal_source,country,currency,tender_id,buyer,title,substr(scope_summary,1,1600) scope_excerpt,main_cpv,cpv_description,reference_value,bidder_count,procedure_text FROM p QUALIFY row_number() over(partition by info_family,delivery_flag,signal_source,country,currency order by reference_value desc nulls last,tender_id)<=15 ORDER BY info_family,country,currency,reference_value DESC NULLS LAST""").fetchall();write(out/'examples.csv',['info_family','delivery_flag','signal_source','country','currency','tender_id','buyer','title','scope_excerpt','main_cpv','cpv_description','reference_value','bidder_count','procedure'],examples)
 excluded=con.execute("SELECT info_family,count(*) records FROM c WHERE delivery_flag='SEMANTIC_COLLISION_OR_EQUIPMENT' GROUP BY 1 ORDER BY 2 DESC").fetchall();write(out/'excluded_classification_matches_preserved.csv',['info_family','records_preserved_for_reclassification'],excluded)
 summary={'version':'HISTORICAL_INFORMATION_WORK_PRECISION_V2','archive_records_scanned':con.execute('select count(*) from hh').fetchone()[0],'classified_before_collision_exclusion':con.execute('select count(*) from c').fetchone()[0],'precision_rows':con.execute('select count(*) from p').fetchone()[0],'families':dict(con.execute('select info_family,count(*) from p group by 1 order by 2 desc').fetchall()),'delivery_flags':dict(con.execute('select delivery_flag,count(*) from p group by 1 order by 2 desc').fetchall()),'signal_sources':dict(con.execute('select signal_source,count(*) from p group by 1 order by 2 desc').fetchall()),'excluded_classification_matches_preserved':con.execute("select count(*) from c where delivery_flag='SEMANTIC_COLLISION_OR_EQUIPMENT'").fetchone()[0],'v1_supersession':'v1 broad family counts remain preserved; v2 is precision authority for semantic promotion. Generic procurement catalogue and medical scanner collisions are intentionally excluded from these classifications, not deleted.','grain':'NOTICE_FIRST_TENDER','historical_only':True,'record_deletion':False,'live_used':False,'dce_used':False}
 (out/'summary.json').write_text(json.dumps(summary,indent=2,ensure_ascii=False),encoding='utf-8')
 lines=['# Historical Information-Work Precision v2','',f"- Global Core records scanned **{summary['archive_records_scanned']:,}** · precision rows **{summary['precision_rows']:,}**",f"- classification collisions excluded but preserved **{summary['excluded_classification_matches_preserved']:,}**",'', 'v2 is the precision authority for promotion. v1 is preserved as a recall/discovery layer.','']
 for r in fam:
  family,n,buy,med,bid,sup,share=r;lines += [f'## {family}',f'- records **{n}** · buyers **{buy}** · median **{med if med is not None else "UNKNOWN"}** · median bidders **{bid if bid is not None else "UNKNOWN"}** · suppliers **{sup if sup is not None else "UNKNOWN"}** · top supplier share **{round(100*share,1) if share is not None else "UNKNOWN"}%**','']
 (out/'REPORT.md').write_text('\n'.join(lines),encoding='utf-8')
if __name__=='__main__':main()
